# Generated by Django 6.0.5 on 2026-05-28 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('SAP', 'SAP'), ('UTILITY', 'UTILITY'), ('TRAVEL', 'TRAVEL')], max_length=50)),
                ('uploaded_file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esg_ingestion.company')),
            ],
        ),
        migrations.CreateModel(
            name='NormalizedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('activity_value', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('emissions_kg_co2e', models.FloatField(blank=True, null=True)),
                ('suspicious', models.BooleanField(default=False)),
                ('review_status', models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esg_ingestion.company')),
            ],
        ),
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('UPDATED', 'UPDATED')], max_length=50)),
                ('performed_by', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esg_ingestion.normalizedrecord')),
            ],
        ),
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_json', models.JSONField()),
                ('ingestion_status', models.CharField(default='PENDING', max_length=50)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esg_ingestion.datasource')),
            ],
        ),
        migrations.AddField(
            model_name='normalizedrecord',
            name='source_record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='esg_ingestion.rawrecord'),
        ),
    ]
